### ISSUE TITLE
Known Problems

### ISSUE THREAD

**Issue by CryoRig** [CryoRig/netdata-homeassistant-addon#1]
LAST UPDATE: 27.09.2023

Looks like we have a new option for  Netdata🎉  
@felipecrs created his own Netdata addon for HA, let's hope he has more time to maintain it than me 🤣  
I haven't tested it yet, so ymmv. 
[His comment](https://github.com/CryoRig/netdata-homeassistant-addon/issues/1#issuecomment-1736657103)

- [ ] Every start of the Container Netdata sees a new Node (no persistence of /etc/netdata)
- [ ] If the container is started without a config, subsequent starts fail.
- [ ] Claim Node without Room
- [x] no fixed Netdata version set
- [x] GH Actions sometimes sets the latest tag for DEV Image
- **DEV Version: it's where i test things and most of the time it won't work. Use at your own Risk...  
That said, i dont think you can actually damage anything...**

**Comment by felipecrs** [comment]
Hey @CryoRig, I'd just like to mention that I started my own version of the Netdata add-on:

https://github.com/felipecrs/netdata-hass-addon

All your known issues are addressed there, as far as I know.
