### ISSUE TITLE
Cannot login to cloud because it is embeded

### ISSUE THREAD

**Issue by roofuskit** [CryoRig/netdata-homeassistant-addon#11]
Netdata's login procedure blocks the page from loading if it is embedded. Anyone know how to get around this? I haven't used add-ons very long using the default netdata port with my hassos IP doesn't seem to work to access it directly.

**Comment by CryoRig** [comment]
Can you post a screenshot of the error? i don't understand what you mean...

**Comment by CryoRig** [comment]
Closing as you haven't updated your Issue with anything that would help me reproduce your problem...
Feel free to reopen when you have something...

**Comment by stncttr908** [comment]
This is macOS Safari, but if you open the add-on in the frame then right click you get the option to open the frame in a new tab or window. From there login works fine.
